### ISSUE TITLE
Feature Request Review

### ISSUE THREAD

**Issue by mml1** [jsharris1229/bwa-u4-feature-request#1]
Great work! Your feature request is concise and proposed a simple solution to improve the user experience. Your approach for the implementation of a visual indicator for songs that are already in the playlist is clear and well-justified. Furthermore, your mockup of the proposed feature definitely adds to your proposal. When presenting features, having a mockup/visuals will go far in making the rest of the team or client understand the feature.

My main feedback is in your technical design. Be sure to add outside resources that support a feature request to make the request, for example where did you get the number about human memory retention? Furthermore, you may want to add a resource to why you selected the colors for the song information. Color theory plays a huge role in design and having a resource on it will help make your case. Someone may argue that instead of using color to make the title pop out, we could just have the song information be really dimmed and not clickable. I like your use of color, but I think if you had a supporting documents about color theory, your presentation will be stronger. An engineer who can communicate well is very valuable in the field and supporting documents for your feature will help with communication. 

Overall, brilliant work 👍

**Comment by jsharris1229** [comment]
Thank you for the review! I agree, I could have done better research on the memory. I was using terms from classes in step-wise refinement, years ago.  A better reference is https://www.simplypsychology.org/short-term-memory.html, which say people can keep 7 items, plus or minus 2, in sort term memory for about 15-30 seconds. I'd have to do more research on colors. Thanks again for your time and comments! 
Stuart
